import React from 'react';
import {
  X,
  User,
  Calendar,
  Activity,
  Heart,
  Wind,
  Thermometer,
  FileText,
  Download,
  FileSpreadsheet,
  Printer,
  BarChart2
} from 'lucide-react';
import { useTheme } from '../../context/ThemeContext';
import { mpisPatientDatabase } from '../../data/sampleData';

const PatientQuickView = ({ patient, triage, isOpen, onClose, onExportPDF, onExportCSV, onViewChart }) => {
  const { isDark, accent } = useTheme();

  if (!isOpen || !patient) return null;

  const handleExportPDF = () => {
    // Generate PDF content
    const pdfContent = {
      patient: {
        name: patient.name,
        age: patient.age,
        gender: patient.gender,
        nsn: patient.nsn,
      },
      vitals: triage?.vitals,
      chiefComplaint: triage?.chiefComplaint,
      exportDate: new Date().toISOString()
    };

    // Get historical vitals from MPIS if available
    const mpisRecord = patient.nsn ? mpisPatientDatabase[patient.nsn] : null;
    const vitalsHistory = mpisRecord?.mpisData?.vitalsHistory || [];

    // Build vitals history section for PDF
    let vitalsHistoryText = '';
    if (vitalsHistory.length > 0) {
      vitalsHistoryText = `

VITALS HISTORY (Last ${vitalsHistory.length} readings)
----------------------------------------`;
      vitalsHistory.forEach(v => {
        vitalsHistoryText += `
${v.date}: BP ${v.bpSystolic}/${v.bpDiastolic} | HR ${v.hr} | SpO2 ${v.spo2}% | Weight ${v.weight}kg`;
      });
    }

    // Create a simple text-based PDF download
    const content = `
PATIENT SUMMARY REPORT
======================
Generated: ${new Date().toLocaleDateString('en-MY', { dateStyle: 'full' })}

PATIENT INFORMATION
-------------------
Name: ${patient.name}
Age: ${patient.age} years old
Gender: ${patient.gender}
NRIC: ${patient.nsn}

VITAL SIGNS
-----------
Blood Pressure: ${triage?.vitals?.bp || 'N/A'}
Heart Rate: ${triage?.vitals?.hr || 'N/A'} bpm
SpO2: ${triage?.vitals?.spo2 || 'N/A'}%
Temperature: ${triage?.vitals?.temp || 'N/A'}°C
Respiratory Rate: ${triage?.vitals?.rr || 'N/A'} /min

CHIEF COMPLAINT
---------------
${triage?.chiefComplaint || 'N/A'}
${vitalsHistoryText}

---
Report generated by CPG LLM - Connecting Values in Healthcare
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `patient_${patient.nsn}_summary.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    if (onExportPDF) onExportPDF(pdfContent);
  };

  const handleExportCSV = () => {
    const headers = ['Field', 'Value'];
    const rows = [
      ['Name', patient.name],
      ['Age', patient.age],
      ['Gender', patient.gender],
      ['NRIC', patient.nsn],
      ['Blood Pressure', triage?.vitals?.bp || 'N/A'],
      ['Heart Rate', `${triage?.vitals?.hr || 'N/A'} bpm`],
      ['SpO2', `${triage?.vitals?.spo2 || 'N/A'}%`],
      ['Temperature', `${triage?.vitals?.temp || 'N/A'}°C`],
      ['Respiratory Rate', `${triage?.vitals?.rr || 'N/A'} /min`],
      ['Chief Complaint', triage?.chiefComplaint || 'N/A'],
      ['Export Date', new Date().toISOString()]
    ];

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `patient_${patient.nsn}_data.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    if (onExportCSV) onExportCSV();
  };

  const getBPColor = (status) => {
    const colors = {
      normal: 'text-emerald-500',
      high: 'text-amber-500',
      critical: 'text-red-600 font-bold'
    };
    return colors[status] || (isDark ? 'text-white' : 'text-slate-800');
  };

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/50 backdrop-blur-sm z-[60] transition-opacity"
        onClick={onClose}
      />

      {/* Modal */}
      <div className={`fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-[70]
        w-full max-w-lg max-h-[90vh] overflow-auto
        rounded-2xl shadow-2xl
        ${isDark
          ? 'bg-slate-900 border border-white/10'
          : 'bg-white border border-slate-200'
        }`}
      >
        {/* Header */}
        <div className={`sticky top-0 flex items-center justify-between p-4 border-b
          ${isDark ? 'bg-slate-900 border-white/10' : 'bg-white border-slate-200'}`}>
          <h2 className={`text-lg font-semibold flex items-center gap-2
            ${isDark ? 'text-white' : 'text-slate-800'}`}>
            <User className={`w-5 h-5 ${accent.text}`} />
            Patient Quick View
          </h2>
          <button
            onClick={onClose}
            className={`p-2 rounded-lg transition-colors
              ${isDark ? 'hover:bg-white/10 text-slate-400 hover:text-white'
                : 'hover:bg-slate-100 text-slate-500 hover:text-slate-800'}`}
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          {/* Patient Info Card */}
          <div className={`p-4 rounded-xl ${isDark ? 'bg-white/5' : 'bg-slate-50'}`}>
            <div className="flex items-center gap-4">
              <div className={`w-16 h-16 rounded-full flex items-center justify-center text-2xl font-bold
                bg-gradient-to-br ${accent.gradient} text-white`}>
                {patient.name?.charAt(0) || 'P'}
              </div>
              <div>
                <h3 className={`text-xl font-semibold ${isDark ? 'text-white' : 'text-slate-800'}`}>
                  {patient.name}
                </h3>
                <p className={`text-sm ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                  {patient.age} y/o • {patient.gender} • {patient.nsn}
                </p>
              </div>
            </div>
          </div>

          {/* Vitals Grid */}
          {triage?.vitals && (
            <div>
              <h4 className={`text-sm font-medium uppercase mb-3 ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                Vital Signs
              </h4>
              <div className="grid grid-cols-2 gap-3">
                <div className={`p-3 rounded-lg ${isDark ? 'bg-white/5' : 'bg-slate-50'}`}>
                  <div className="flex items-center gap-2 mb-1">
                    <Activity className="w-4 h-4 text-red-500" />
                    <span className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Blood Pressure</span>
                  </div>
                  <p className={`text-lg font-semibold ${getBPColor(triage.vitals.bpStatus)}`}>
                    {triage.vitals.bp} mmHg
                  </p>
                </div>
                <div className={`p-3 rounded-lg ${isDark ? 'bg-white/5' : 'bg-slate-50'}`}>
                  <div className="flex items-center gap-2 mb-1">
                    <Heart className="w-4 h-4 text-pink-500" />
                    <span className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Heart Rate</span>
                  </div>
                  <p className={`text-lg font-semibold ${isDark ? 'text-white' : 'text-slate-800'}`}>
                    {triage.vitals.hr} bpm
                  </p>
                </div>
                <div className={`p-3 rounded-lg ${isDark ? 'bg-white/5' : 'bg-slate-50'}`}>
                  <div className="flex items-center gap-2 mb-1">
                    <Wind className="w-4 h-4 text-blue-500" />
                    <span className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>SpO2</span>
                  </div>
                  <p className={`text-lg font-semibold ${isDark ? 'text-white' : 'text-slate-800'}`}>
                    {triage.vitals.spo2}%
                  </p>
                </div>
                <div className={`p-3 rounded-lg ${isDark ? 'bg-white/5' : 'bg-slate-50'}`}>
                  <div className="flex items-center gap-2 mb-1">
                    <Thermometer className="w-4 h-4 text-orange-500" />
                    <span className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Temperature</span>
                  </div>
                  <p className={`text-lg font-semibold ${isDark ? 'text-white' : 'text-slate-800'}`}>
                    {triage.vitals.temp}°C
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* Chief Complaint */}
          {triage?.chiefComplaint && (
            <div>
              <h4 className={`text-sm font-medium uppercase mb-3 ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                Chief Complaint
              </h4>
              <div className={`p-4 rounded-lg ${isDark ? 'bg-white/5' : 'bg-slate-50'}`}>
                <p className={`${isDark ? 'text-white' : 'text-slate-800'}`}>
                  {triage.chiefComplaint}
                </p>
              </div>
            </div>
          )}

          {/* Export Buttons */}
          <div className={`pt-4 border-t ${isDark ? 'border-white/10' : 'border-slate-200'}`}>
            <h4 className={`text-sm font-medium uppercase mb-3 ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
              Export Options
            </h4>
            <div className="flex gap-3">
              <button
                onClick={handleExportPDF}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-lg font-medium transition-all
                  bg-gradient-to-r ${accent.gradient} text-white shadow-lg ${accent.shadow}
                  hover:opacity-90`}
              >
                <FileText className="w-4 h-4" />
                Export PDF
              </button>
              <button
                onClick={handleExportCSV}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-lg font-medium transition-all
                  ${isDark
                    ? 'bg-white/10 hover:bg-white/20 text-white border border-white/10'
                    : 'bg-slate-100 hover:bg-slate-200 text-slate-700 border border-slate-200'}`}
              >
                <FileSpreadsheet className="w-4 h-4" />
                Export CSV
              </button>
            </div>

            {/* View Chart Button */}
            {onViewChart && (
              <button
                onClick={() => {
                  onClose();
                  onViewChart(patient);
                }}
                className={`w-full mt-3 flex items-center justify-center gap-2 px-4 py-3 rounded-lg font-medium transition-all
                  ${isDark
                    ? 'bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-400 border border-emerald-500/30'
                    : 'bg-emerald-50 hover:bg-emerald-100 text-emerald-700 border border-emerald-200'}`}
              >
                <BarChart2 className="w-4 h-4" />
                View Vital Signs Chart
              </button>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default PatientQuickView;
